'''
Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
python
   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.
'''


evennumbersum = 0
fibterm3 = 3
fibterm2 = 2
fibterm1 = 1
latestevennum = 0

while fibterm3 <= 4000000:
	
	fibterm3 = fibterm2 + fibterm1
	fibterm1 = fibterm2
	fibterm2 = fibterm3
	if fibterm1 % 2 == 0:
		evennumbersum = evennumbersum + fibterm1
		latestevennum = fibterm1
	print (str(fibterm3) + " " + str(latestevennum) + " " + str(evennumbersum)) 
	

#evennumbersum = evennumbersum - latestevennum	
print (str(evennumbersum))	